//alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

//auth
// export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
// export const REGISTER_FAIL = "REGISTER_FAIL";

// export const AUTH_SUCCESS = "AUTH_SUCCESS";
// export const AUTH_FAILURE = "AUTH_FAILURE";

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAILURE = 'AUTHENTICATED_FAILURE';

export const UPDATE_CURRENT_GAME_WEEK = 'UPDATE_CURRENT_GAME_WEEK';
export const UPDATE_CURRENT_GAME_WEEK_FAIL = 'UPDATE_CURRENT_GAME_WEEK_FAIL';
